### ISSUE TITLE
Incomplete variable extraction

### ISSUE THREAD

**Issue by kmpaul** [NCAR/PyReshaper#20]
From Chengfei He (@yefee):

"...can pyrehsaper extract only single variable in CESM output? Since our output has several hundred TB, extracting all variables is not time-efficient."

**Comment by kmpaul** [comment]
Extraction of a single variable from CESM output is not what PyReshaper was designed to do, and that may require some explanation.  Please forgive me for explaining something that may seem obvious...

PyReshaper was designed as a tool to help transform _complete_ CESM component output from its natural _history_file_ format into _time-series_ format.  Handling one single variable at a time, which is required by NCO and NCL scripts, was terribly inefficient, so we decided to write the PyReshaper to handle all of the variables in a given dataset _in_parallel_.

Due to its current design, the PyReshaper parallelizes over variables.  That means performance _only_ improves when the operation is done on many variables at once, and maximum performance is obtained when enough MPI ranks are used to guarantee that all of the _largest_ variables in the dataset are given their own MPI rank.  Applying PyReshaper on only 1 time-series variable is no different than applying equivalent serial NCO or NCL scripts to extract that same variable.  It should not, in principle, go any faster.

Second, the CESM transformation of _complete_ component datasets is currently an expected part of the CESM workflow, since the data that is archived is expected to be in _time-series_ format.  After transformation from _history-file_ format to _time-series_ format, the history files are expected to be (eventually) deleted.  Hence, to avoid accidental loss of data, we designed the PyReshaper to _never_ allow the user to transform only part of the dataset.  For that reason, I have been hesitant to implement this feature.

That said, when working with very large datasets (such as yours) _and_ when _many_ variables must be extracted (though not _all_ of the variables), it would be more time-efficient to use the PyReshaper.  Due to space limitations, too, it makes sense to only extract some of the variables that are needed.

However, I might be more inclined to suggest that if someone has a very large CESM dataset, and they want to perform a great deal of analysis on that data, then I might suggest transforming the entire dataset into time-series format (with PyReshaper) _once_ (and _only_ once), and then deleting the original CESM dataset before doing more analysis.  

Can you explain to me how you are using the PyReshaper such that this usage policy (i.e., transform the entire dataset, delete the original, and then do analysis) is not sufficient?

**Comment by Yefee** [comment]
Thanks for your explanation! This is mainly why you call it pyReshaper.
Actually, not all the variables in CESM output are needed in our case. We ate just interested in some of them. Reshaping all variables into time series file shall take lots of time and space, which is sometimes impossible. I think we can use nco instead. Thanks!

**Comment by kmpaul** [comment]
Thanks for getting back to me.  If NCO will work for you to extract just a handful of variables, then I would suggest that route.  However, if you find that NCO is insufficient for your needs, please let me know!  I will prioritize implementing a solution for you.

Until then, I will keep this issue open until I know for certain that it is needed or not needed.

**Comment by kmpaul** [comment]
With Pull Request #24, this issue is closed.  I have now added the ability to extract out specific variables into time-series files, instead of the entire dataset.
