### ISSUE TITLE
Chunking with --chunk is ignored

### ISSUE THREAD

**Issue by adrfantini** [NCAR/PyReshaper#38]
I am trying to transform a single file from time-slice to time-series, and I'd want the output to be chunked so that reading a time series from the file is very fast.

To accomplish this, from my understanding of the manual, I have to issue a command like so:

```
./s2smake --time_series por input.nc;  ./s2srun --chunk time,100 --chunk lat,1 --chunk lon,1 --serial --verbosity 2 input.s2s
```

However, the output chunk sizes are: `por:_ChunkSizes = 1, 280, 678`

What am I missing here?

I am using version 1.0.5 installed with Pip.

**Comment by kmpaul** [comment]
Yes.  I apologize for the confusion.  The `chunk` argument to `s2srun` does not refer to the NetCDF chunk-sizes written to the file.  It refers to the "chunk" sizes that are *read* from the input file (and are then immediately written to the new files).  As a result, the `chunk` parameter is primarily used to limit memory use, but it has nothing to do with the chunk size within the file.

I'm sorry for the confusion.

If you need to rechunk your files after creation, I might point you here:

https://sourceforge.net/p/nco/discussion/9830/thread/3d011aa0/

**Comment by adrfantini** [comment]
Thanks for popping by! Then the manual is incorrect, as it states:
> `--chunk NAME,SIZE (-c NAME,SIZE)`: This command-line option can be used to specify a maximum read/**write** chunk-size `SIZE` along a given named dimension `NAME`

If I might be allowed an opinion, I think that setting write chunks would be a useful feature for all those variables that need to be analyzed as time-series for single cells. In my case, for example, I need to analyze time-series of discharge from a distributed hydrological model, only for specific cells (where the observational stations are).

**Comment by kmpaul** [comment]
Yes.  That's a valid complaint.  I should change the manual to indicate "read chunk-size" only.

So, a valid solution to your problem, then, would be to just have the Reshaper set the file chunk-size to match the chunk-size set by the user?  In other words, if the manual was actually correct (or, at least, not misleading), that would work for you?

**Comment by adrfantini** [comment]
I would say that would be useful for me, but I'm not sure that having one single chunk spec for read and write is the best solution - maybe having them separate is the best thing.

Say for example the input files are already chunked  `1,10,10` and one wants the output to be chunked `1000,1,1`. In this case setting the input chunking to `1000,10,10` would - if I understand this correctly, and I might not! - lead the best result speed-wise, at the cost of having to read and store 1000 chunks at a time from the input file. If memory is limited one them might want to set input chunking to something like `10,1,1` and throw away some data for each read.

Again, I'm not sure which way pyReshaper is set up so I don't know if this design decision has been taken already.

**Comment by kmpaul** [comment]
I agree that splitting the read-chunk and write-chunk should be done.  It's a little more work, but it's not a problem.  I'll put that on my list of "to do" items, and I'll reply back when I have it done.

**Comment by adrfantini** [comment]
Awesome, thanks!

**Comment by kmpaul** [comment]
@adrfantini Would you be willing to test the 'devel' branch of PyReshaper to see if it work for you?  I have not updated the documentation, but I have changed to code to accept separate read- or write-chunking parameters.  With this change, the `s2srun` command's `--chunk` is gone.  It now has `--read_chunk` and `--write_chunk` options, that work just like the previous `--chunk` option works.

Now that I think about it, I might need to accept `--chunk` for backwards compatibility, but if you can test the devel branch, that would be very helpful.  (And, if you can, can you tell me performance numbers?  Does it operate as quickly as you hope?)

**Comment by adrfantini** [comment]
I sure will! I'm not sure I can manage today, but I will try!

**Comment by adrfantini** [comment]
Testing. The [test file](http://s000.tinyupload.com/download.php?file_id=06767161020989975305&t=0676716102098997530559219) is a small sample, `5x280x678` in size and chunked `1, 96, 678`. Dimensions are `time, lat, lon`. Compression is 1 and compressed size is ~15MB for the whole file, but I select only one variable (a float).

Take these numbers with a grain of salt, since for most tests I did not repeat the runs several times. The machine is I/O limited to `70MB/s` and there are other (constant) I/O running at the same time. Sorry, but I could not test in a cleaner environment. The numbers below should still be a useful reference, I think.

Make command: `./s2smake --time_series por nc.nc` (convert one single variable named `por`)

Run commands, final chunk sizes and benchmarks:

**1. ./s2srun --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 1, 280, 678
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.38554382324e-05
Specifier Validation:              3.81469726562e-05
Complete Conversion Process:       0.194218158722
Inspect Input Files:               0.00422501564026
Inspect Output Files:              0.000225067138672
Open Output Files:                 0.00153207778931
Close Output Files:                0.0674901008606
Open Input Files:                  0.00332808494568
Close Input Files:                 0.000327110290527
Create Time-Invariant Metadata:    0.0360250473022
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.0110268592834
Read Time-Invariant Metadata:      0.000797986984253
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.00457000732422
Write Time-Invariant Metadata:     0.000435829162598
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       0.00136184692383
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     36.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  46.7421875
--------------------------------------------------
```
**2. ./s2srun -w time,5 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 5, 96, 678 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.40938568115e-05
Specifier Validation:              3.60012054443e-05
Complete Conversion Process:       0.195838928223
Inspect Input Files:               0.00501203536987
Inspect Output Files:              0.000641107559204
Open Output Files:                 0.00071907043457
Close Output Files:                0.0653669834137
Open Input Files:                  0.00315499305725
Close Input Files:                 0.000464916229248
Create Time-Invariant Metadata:    0.0324850082397
Create Time-Variant Metadata:      0.0
Create Time-Series Variables:      0.0132369995117
Read Time-Invariant Metadata:      0.000816106796265
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.00411558151245
Write Time-Invariant Metadata:     0.00043511390686
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       0.0021607875824
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     36.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  47.62109375
--------------------------------------------------
```
**3. ./s2srun -w time,5 -w lat,10 -w lon,10 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 5, 10, 10 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.50475311279e-05
Specifier Validation:              3.60012054443e-05
Complete Conversion Process:       10.61480093
Inspect Input Files:               0.0134329795837
Inspect Output Files:              0.00384593009949
Open Output Files:                 0.00119614601135
Close Output Files:                1.54034209251
Open Input Files:                  0.00381302833557
Close Input Files:                 0.000468969345093
Create Time-Invariant Metadata:    0.0373508930206
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.0390870571136
Read Time-Invariant Metadata:      0.000792741775513
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.00676560401917
Write Time-Invariant Metadata:     0.000442743301392
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       8.86231899261
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     36.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  57.4765625
--------------------------------------------------
```
**4. ./s2srun -w time,5 -w lat,1 -w lon,1 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 5, 1, 1 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.40938568115e-05
Specifier Validation:              3.60012054443e-05
Complete Conversion Process:       727.181874037
Inspect Input Files:               0.00439286231995
Inspect Output Files:              0.000578880310059
Open Output Files:                 0.000576019287109
Close Output Files:                0.676457166672
Open Input Files:                  0.00345611572266
Close Input Files:                 0.000708103179932
Create Time-Invariant Metadata:    0.0281798839569
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.00972509384155
Read Time-Invariant Metadata:      0.000868558883667
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.982170581818
Write Time-Invariant Metadata:     0.000509738922119
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       725.154508114
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     36.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  1149.80859375
--------------------------------------------------
```

**5. ./s2srun -w time,4000 -w lat,10 -w lon,10 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 4000, 10, 10 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.38554382324e-05
Specifier Validation:              3.69548797607e-05
Complete Conversion Process:       78.3794679642
Inspect Input Files:               0.00455784797668
Inspect Output Files:              0.000601053237915
Open Output Files:                 0.00068998336792
Close Output Files:                0.029846906662
Open Input Files:                  0.00322484970093
Close Input Files:                 0.000322103500366
Create Time-Invariant Metadata:    0.0292310714722
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.0115070343018
Read Time-Invariant Metadata:      0.000790357589722
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.00682711601257
Write Time-Invariant Metadata:     0.00042986869812
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       78.2287890911
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     36.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  63.46875
--------------------------------------------------
```

**6. ./s2srun -w time,4000 -w lat,1000 -w lon,1000 -c time,5 -c lat,280 -c lon,678 --serial --verbosity 2 input.s2s**
```
FAILED : ValueError: chunksize cannot exceed dimension size
```

**7. ./s2srun -w time,5 -w lat,1 -w lon,1 -c time,5 -c lat,280 -c lon,678 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 5, 1, 1 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.50475311279e-05
Specifier Validation:              3.79085540771e-05
Complete Conversion Process:       149.827688932
Inspect Input Files:               0.0048840045929
Inspect Output Files:              2.50339508057e-05
Open Output Files:                 0.00204610824585
Close Output Files:                0.462329864502
Open Input Files:                  0.00358414649963
Close Input Files:                 0.217932939529
Create Time-Invariant Metadata:    0.0284240245819
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.0102119445801
Read Time-Invariant Metadata:      0.000811100006104
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.00420308113098
Write Time-Invariant Metadata:     0.000458240509033
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       149.022399902
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     20.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  1148.2265625
--------------------------------------------------
```

**8. ./s2srun -w time,5 -w lat,10 -w lon,10  -c time,5 -c lat,280 -c lon,678 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 5, 10, 10 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.09944152832e-05
Specifier Validation:              3.50475311279e-05
Complete Conversion Process:       1.5295009613
Inspect Input Files:               0.00431394577026
Inspect Output Files:              0.000284910202026
Open Output Files:                 0.000645875930786
Close Output Files:                0.387958049774
Open Input Files:                  0.00242900848389
Close Input Files:                 0.00107312202454
Create Time-Invariant Metadata:    0.0132129192352
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.00494599342346
Read Time-Invariant Metadata:      0.0238921642303
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.673739910126
Write Time-Invariant Metadata:     0.000516891479492
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       0.386098146439
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     20.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  58.5625
--------------------------------------------------
```

**9. ./s2srun -w time,5 -w lat,10 -w lon,10  -c time,5 -c lat,28 -c lon,68 --serial --verbosity 2 input.s2s**
```
por:_ChunkSizes = 5, 10, 10 ;
--------------------------------------------------
 TIMING DATA:
--------------------------------------------------
Initializing Simple Communicator:  3.21865081787e-05
Specifier Validation:              3.50475311279e-05
Complete Conversion Process:       1.35549998283
Inspect Input Files:               0.0093891620636
Inspect Output Files:              0.000454902648926
Open Output Files:                 0.000789880752563
Close Output Files:                0.733556985855
Open Input Files:                  0.00243616104126
Close Input Files:                 0.000296115875244
Create Time-Invariant Metadata:    0.0264880657196
Create Time-Variant Metadata:      9.53674316406e-07
Create Time-Series Variables:      0.00520610809326
Read Time-Invariant Metadata:      0.00332188606262
Read Time-Variant Metadata:        0.0
Read Time-Series Variables:        0.0266695022583
Write Time-Invariant Metadata:     0.00199699401855
Write Time-Variant Metadata:       0.0
Write Time-Series Variables:       0.50759601593
--------------------------------------------------

--------------------------------------------------
 BYTE COUNTS (MB):
--------------------------------------------------
Actual Data:     488.0
Requested Data:  3.62502288818
--------------------------------------------------

--------------------------------------------------
 MEMORY USAGE (MB):
--------------------------------------------------
Maximum Memory Use:  44.41015625
--------------------------------------------------
```

Things to note, a bit jumbled up:

1. time is still UNLIMITED. An option to set time to fixed dimension might speed things up, at the cost of not appending
2. Setting write chunks bigger than the dimension fails (test 6), except for time (as it's unlimited, I guess). Being able to force the chunks to be the maximum size possible would be nice, e.g. by setting the chunk size to 0. Test 5 is much slower than 3 due to the extreme chunking in time.
3. For this small dataset setting small lat-lon chunks (test 4) results in a huge decrease in performance and increase in memory usage. This might change for datasets which have longer times.
4. A total timer would be useful!
5. When using small write chunks, the amount of memory used is huge compared to the size of the variable, which should be just a few MB uncompressed.
6. Comparing test 7 with test 4, setting read chunks improves performance, but memory usage is still over the roof for some reason.
7. Setting read chunks does not seem to make much difference (test 3 vs test 8 vs test 9).
8. Since there is a `-d` option for truncating data, data should be automatically set to integer if `-d 0` is passed.

Sorry if this is a bit messy. Let me know if I can do some more relevant test. In the meantime I'll start experimenting on bigger files.

**Comment by adrfantini** [comment]
Doing the same as test 3 (see above) for a similar file, but with 720 timesteps, has proven to be extremely slow. It has been running for several hours now.

Using instead `-w time,721 -w lat,10 -w lon,10 -c time,721 -c lat,280 -c lon,678`, which in my mind should read the complete file once, then write it in chunks, uses a large amount of memory (1.1GB) but is fast (a couple of minutes max).

Using `-w time,721 -w lat,1 -w lon,1 -c time,721 -c lat,280 -c lon,678`, which would be the ideal output in my case, takes longer (5-6 minutes) and lots of memory (1.7GB). Compared to a custom script where I read all the data and rewrite it to the same file with `721,1,1` chunking, this is a bit slower (for a single file at least). I am willing to live with that personally.

**Comment by kmpaul** [comment]
@adrfantini Yes, you are starting to uncover the mysteries of chunking.  I must admit that I am not an expert myself, but I know that (1) chunking can have an enormous impact on performance and (2) it is not always obvious what the best chunking should be.  I wish I could tell you what the correct solution should be, but I cannot.

Now, let me address your 8 points in your previous post:

1. Yes.  The dimension type is preserved (unlimited vs limited), but changing it seems relatively easy to do.  Something like a single `s2srun` boolean option like `--limit_dimensions` would do the trick, and produce only limited dimensions in the output.  ...Though I'm not sure how much work that would be.  Maybe you could create a new issue for that request?

2. I believe this should be the correct behavior, though.  The chunking parameters set by the user are passed directly to the NetCDF library, and I believe that the NetCDF library should make the decision as to whether the chunking you provide is sensible.  Do you agree?

3. Yes.  This makes sense to me.  Setting a very small chunk size in the faster-changing dimensions will be a huge hit to performance.   Though, if you are running on a platform with a very small filesystem block size, you might not see as bad of a hit to performance.

4. What do you mean by "total timer"?  The `Complete Conversion Process` item in the `TIMING DATA` section at the end of the run is meant to measure the total time to run the `convert` function of Reshaper.

5. Yes.  This is a factor of the buffering layers handled by the NetCDF/HDF5 layer below the Reshaper.  I am positive that this could be optimized, but it is out of the scope of the Reshaper.

6. See the answer for 5.  This has to do with the I/O layers underneath the Reshaper.

7.  In memory use, you are correct, but test 3 runs in 10+ seconds and test 8 and test 9 run in about 1.5 seconds.

8. Are you suggesting that the output type of the data (the numpy dtype) be changed to `int` when truncation is done with `least_significant_digit = 0`?  I would disagree.  With floating point numbers, the numeric range is different than it is for integers.  If the user wanted to do something like this, then using the CF attributes `scale` and `offset` should be used, instead.  I believe that the dtype of the data should be preserved, and truncation should only be used as a "trick" to achieve greater compression rates.  (Note: this is still an experimental feature, too.)

**Comment by kmpaul** [comment]
@adrfantini It does appear, though, that this chunking feature is working, even if it is not very predictable.  Rather, the chunksizes of the output data are what you expect them to be, correct?  If that's true, do you consider this feature "complete"?

**Comment by adrfantini** [comment]
@kmpaul 
Thanks for the replies. Yes, I do think that the feature works as advertised, even though I was expecting lower memory usage. But if this is due to the library then I guess not much can be done about it. You can close this if you wish so.

1. Yep, I will.
2. Matter of opinion I guess. Maybe the best middle ground is exiting with error when the chunking value is too big, but allowing for a value (e.g. 0) which automatically select the bigger chunk possible.
3. Indeed, especially if the FS is NFS, where the block size is often <32k
4. Whoops, missed that, was expecting it to be at the bottom!
8. Uhm, you are right about the numeric range. However, even greater compression can be achieved with integers for those cases where float precision is not needed. Other software offers optional flags for this (e.g. `cdo -b`), but I agree this is a feature that would rarely be used.
