### ISSUE TITLE
PyReshaper seems to assume times are relative to the same epoch

### ISSUE THREAD

**Issue by adrfantini** [NCAR/PyReshaper#40]
I have two files which I want to process using PyReshaper.

For the first the units are "seconds since 2016-11-01 00:00:00 UTC", while for the second they are  "seconds since 2016-12-01 00:00:00 UTC". There is no overlap, the first file ends at `2016-11-30 23:00:00 UTC` and the second begins at `2016-12-01 00:00:00 UTC`.

Nevertheless, the values of the variable `time` for the two files are identical: only the epoch changes.

When trying to run `s2srun` I get the following error, as if the different epoch was ignored:
```
ValueError: Times in input files intdb-fil_reg1_22_2016110100.nc and intdb-fil_reg1_22_2016120100.nc appear to overlap
```

**Comment by kmpaul** [comment]
Yes.  The PyReshaper does not have a mechanism to change reference datetime or calendar.  So, it assumes that every file *must* have the same time units and calendar.

At the time of the writing of the PyReshaper, the complications of dealing with different calendars and reference datetimes was considered "out of the scope" of the project.  (It was designed to convert CESM output produced straight from the model, where the units and calendar are consistent across all time-slice/history files.)

Moving to the handling that you would like, I might suggest that you try out Xarray.  While it's handling of times is still not perfect, it should work for your needs (I think).

Take a look at this awesome project:  
https://github.com/pydata/xarray

**Comment by adrfantini** [comment]
Yeah, xarray is very nice, but not exactly what I was looking for. It shouldn't be too hard to let PyReshaper reference all times to the units of the first file... I'll take a look at it, maybe in a couple weeks.

**Comment by kmpaul** [comment]
@adrfantini If you want to look into it, you might look at `cf_units` or possible at the CF convention decoding that Xarray can do.  In another project, I've used `cf_units` to decode time, but it is still limited (i.e., can't convert times with different calendars).  To be honest, I think that time/calendars are severely lacking in all Python tools right now.  It's something that someone should fix sometime.  :-)

**Comment by adrfantini** [comment]
I use R a lots and it's even worse there, I had to deal with `360_day` calendars and it was quite annoying. As long as the calendar is gregorian `udunits2` works very well tho.

**Comment by adrfantini** [comment]
Unfortunately not, I now work in another field so it's unlikely I'll work on this anytime soon, sorry.

**Comment by kmpaul** [comment]
@adrfantini I am closing this issue.  I believe that the functionality of this is beyond the scope of the reshaper.
