### ISSUE TITLE
Change license to Apache 2.0

### ISSUE THREAD

**Issue by kmpaul** [NCAR/PyReshaper#49]
Our current license is too restrictive to allow true open-source contributions.  So, I propose we change the license to Apache 2.0.  In order to legally do this, though, I need approval from **all** contributors.  Fortunately, that is a short list:

@kmpaul 
@sherimickelson 
@dchandan

Please indicate on this issue (either with a comment or a +1) that you approve of this change.  I can't do anything until I have everyone's approval.

**Comment by CAM-Gerlach** [comment]
@kmpaul I would strongly recommend requiring a comment instead of a :+1: , since it provides a clearer, legally accepted indication, a :+1: can easily be changed after the fact and there is no permanent record of it, unlike for a comment (which keeps a revision history, indicates when it is deleted and sends an immutable email copy out to you assuming you're subscribed the the thread).

**Comment by kmpaul** [comment]
Ah!  Good point, @CAM-Gerlach.  I see you've done this before.

Just so everyone knows, I (obviously) approve changing to Apache 2.0.  What do the rest of you think?  @sherimickelson @dchandan

**Comment by CAM-Gerlach** [comment]
@kmpaul Yep :) I've also had to deal with a variety of different legal and licensing issues during my time as a core dev for Spyder, the Scientific Python Development Environment, an open-source IDE with hundreds of thousands of regular users, hundreds of contributors and dozens of hard and soft dependencies, vendered code, fonts and graphic assets under almost as many different licenses.

**Comment by sherimickelson** [comment]
I agree with changing to Apache 2.0.

**Comment by kmpaul** [comment]
After some time, I vaguely remembered asking @dchandan about licensing back in 2015, when He initially submitted a PR back then, our legal team wanted to implement the restrictive license that the PyReshaper currently has. As a result, to merge his PR, with the existing license, I had to receive approval from him to transfer ownership of his code to NCAR. He approved (I have the email) so I don’t think we need his approval to switch the license. Only the current NCAR owners.

**Comment by CAM-Gerlach** [comment]
If NCAR owns the code, and NCAR approves the switch (as it seems it is official NCAR policy to use Apache 2.0) then that should be fine from a legal perspective (IANAL).

**Comment by CAM-Gerlach** [comment]
@dchandan this is the issue to comment on re: the license, BTW

**Comment by kmpaul** [comment]
This is done with PR #50
